aliases:
  a: tmux attach
  add: todoist add
  be: bundle exec
  berc: bundle exec rails c
  big: echo -e "\033]710;xft:Cousine:pixelsize=38\033\\ \033]711;xft:Cousine:pixelsize=38\033\\ \033]712;xft:Cousine:pixelsize=38\033\\ \033]713;xft:Cousine:pixelsize=38\033\\" && clear
  book: awk 'FNR==1{print ""}1' *.md | kramdown -o pdf >out.pdf 2>/dev/null
  c: clear
  ck: m ck
  d: (cd ~/.dotfiles && vim -c "NERDTreeToggle" bashrc) && up
  dot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" bashrc) && up
  g: git
  kpack: ruby -Ilib ./exe/kpack
  layout: tmux list-windows | sed 's/.*\[layout //' | sed 's/]].*/]/'
  m: tmuxinator
  medium: echo -e "\033]710;xft:Cousine:pixelsize=28\033\\ \033]711;xft:Cousine:pixelsize=28\033\\ \033]712;xft:Cousine:pixelsize=28\033\\ \033]713;xft:Cousine:pixelsize=28\033\\" && clear
  nethack: ssh nethack@alt.org
  p: pwd
  recover: DISPLAY=:0 xdotool windowfocus $(DISPLAY=:0 xdotool search -name rxvt)
  res: echo $(tput cols)x$(tput lines)
  s: tmux switch -t
  signal: google-chrome --app-id=$(basename $(ack 'Signal' .local/share/applications/ -l) | sed 's/-Default.desktop//' | sed 's/chrome-//')
  sign: git config commit.gpgsign true
  small: echo -e "\033]710;xft:Cousine:pixelsize=20\033\\ \033]711;xft:Cousine:pixelsize=20\033\\ \033]712;xft:Cousine:pixelsize=20\033\\ \033]713;xft:Cousine:pixelsize=20\033\\" && clear
  svndiff: 'svn diff --diff-cmd=colordiff --extensions=" -u --strip-trailing-cr --ignore-space-change " | less --quit-if-one-screen'
  t: tmux
  tiny: echo -e "\033]710;xft:Cousine:pixelsize=14\033\\ \033]711;xft:Cousine:pixelsize=14\033\\ \033]714;xft:Cousine:pixelsize=14\033\\ \033]713;xft:Cousine:pixelsize=14\033\\" && clear
  today: script -f -q --command "todoist --color list" | grep --color=never $(date +%y/%m/%d)
  todo: todoist s && todoist --color
  tomorrow: script -f -q --command "todoist --color list" | grep --color=never $(date --date="tomorrow" +%y/%m/%d)
  v: vim
  vdot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" vimrc) && up
  w: find . | grep md | xargs cat | wc -w
  webs: python -m SimpleHTTPServer
  wifi: nmtui
  z: fg
symlinks:
  .vimrc: .dotfiles/vimrc
  .tmux.conf: .dotfiles/tmux.conf
  .gitconfig: .dotfiles/gitconfig
  .gitignore: .dotfiles/gitignore
  .ratpoisonrc: .dotfiles/ratpoisonrc
  .Xdefaults: .dotfiles/Xdefaults
  .ackrc: .dotfiles/ackrc
  .ssh/config: .dotfiles/ssh_config
  .tmuxinator: .dotfiles/tmuxinator
  .gnupg/gpg.conf: .dotfiles/gpg.conf
