aliases:
  be: bundle exec
  berc: bundle exec rails c
  webs: python -m SimpleHTTPServer
  dot: (cd ~/.dotfiles && vim bashrc) && up
  book: awk 'FNR==1{print ""}1' *.md | kramdown -o pdf >out.pdf 2>/dev/null
  m: mux
  z: fg
symlinks:
  .vimrc: .dotfiles/vimrc
  .tmux.conf: .dotfiles/tmux.conf
  .gitconfig: .dotfiles/gitconfig
