aliases:
  be: bundle exec
  berc: bundle exec rails c
  big: echo -e "\033]710;xft:Cousine:pixelsize=38\033\\ \033]711;xft:Cousine:pixelsize=38\033\\ \033]712;xft:Cousine:pixelsize=38\033\\ \033]713;xft:Cousine:pixelsize=38\033\\" && clear
  small: echo -e "\033]710;xft:Cousine:pixelsize=20\033\\ \033]711;xft:Cousine:pixelsize=20\033\\ \033]712;xft:Cousine:pixelsize=20\033\\ \033]713;xft:Cousine:pixelsize=20\033\\" && clear
  branches: for k in `git branch | perl -pe s/^..//`; do echo -e `git show --pretty=format:"%Cgreen%ci %Cblue%cr%Creset" $k -- | head -n 1`\\t$k; done | sort
  webs: python -m SimpleHTTPServer
  nethack: ssh nethack@alt.org
  dot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" bashrc) && up
  vdot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" vimrc) && up
  d: (cd ~/.dotfiles && vim -c "NERDTreeToggle" bashrc) && up
  book: awk 'FNR==1{print ""}1' *.md | kramdown -o pdf >out.pdf 2>/dev/null
  kpack: ruby -Ilib ./exe/kpack
  res: echo $(tput cols)x$(tput lines)
  m: mux
  z: fg
  c: clear
  w: find . | grep md | xargs cat | wc -w
  v: vim
  p: pwd
symlinks:
  .vimrc: .dotfiles/vimrc
  .tmux.conf: .dotfiles/tmux.conf
  .gitconfig: .dotfiles/gitconfig
  .ratpoisonrc: .dotfiles/ratpoisonrc
  .Xdefaults: .dotfiles/Xdefaults
  .ackrc: .dotfiles/ackrc
  .ssh/config: .dotfiles/ssh_config
