aliases:
  a: tmux attach
  add: git add $(history | sed -n 'x;$p' | awk '{print $3}')
  ack: ag
  audio: sudo kill -9 `ps ax|grep 'coreaudio[a-z]' | awk '{print $1}'`
  b: cd $OLDPWD
  be: bundle exec
  c: clear && yes '' | head -10
  dot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" bashrc -c "wincmd w") && up
  format: npx prettier --write
  g: cd $(git rev-parse --show-toplevel)
  layout: tmux list-windows | sed 's/.*\[layout //' | sed 's/]].*/]/'
  m: tmuxinator
  nethack: ssh nethack@alt.org
  rc: bundle exec rails c
  res: echo $(tput cols)x$(tput lines)
  s: tmux switch -t
  t: tmux
  token: stoken | tail -n 1 | pbcopy
  v: vim
  vdot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" vim/vimrc -c "wincmd w") && up
  vide: vim -c "NERDTreeToggle" -c "wincmd w"
  webs: (python -m SimpleHTTPServer || python -m http.server 8000)
  wifi: nmtui
  wiki: vim -c VimwikiIndex
  x: exit
  z: fg
symlinks:
  .Xdefaults: .dotfiles/Xdefaults
  .ackrc: .dotfiles/ackrc
  .gitconfig: .dotfiles/git/gitconfig
  .gitignore: .dotfiles/git/gitignore
  .gnupg/gpg.conf: .dotfiles/gpg.conf
  .ratpoisonrc: .dotfiles/ratpoison/ratpoisonrc
  .ssh/config: .dotfiles/ssh_config
  .tmux.conf: .dotfiles/tmux/tmux.conf
  .tmuxinator: .dotfiles/tmuxinator
  .vimrc: .dotfiles/vim/vimrc
  .vim/after/ftplugin: .dotfiles/vim/ftplugin
