aliases:
  be: bundle exec
  berc: bundle exec rails c
  webs: python -m SimpleHTTPServer
  nethack: ssh nethack@alt.org
  dot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" bashrc) && up
  book: awk 'FNR==1{print ""}1' *.md | kramdown -o pdf >out.pdf 2>/dev/null
  kpack: ruby -Ilib ./exe/kpack
  m: mux
  z: fg
  c: clear
  w: find . | grep md | xargs cat | wc -w
symlinks:
  .vimrc: .dotfiles/vimrc
  .tmux.conf: .dotfiles/tmux.conf
  .gitconfig: .dotfiles/gitconfig
  .ratpoisonrc: .dotfiles/ratpoisonrc
  .Xdefaults: .dotfiles/Xdefaults
