aliases:
  ack: ag
  a: tmux attach
  be: bundle exec
  big: echo -e "\033]710;xft:Cousine:pixelsize=38\033\\ \033]711;xft:Cousine:pixelsize=38\033\\ \033]712;xft:Cousine:pixelsize=38\033\\ \033]713;xft:Cousine:pixelsize=38\033\\" && clear
  btf: while true; do ssh -R 2210:localhost:22 gisikw@kevingisi.com; sleep 10; done
  c: clear && yes '' | head -10
  dot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" bashrc) && up
  format: npx prettier --write
  layout: tmux list-windows | sed 's/.*\[layout //' | sed 's/]].*/]/'
  m: tmuxinator
  medium: echo -e "\033]710;xft:Cousine:pixelsize=28\033\\ \033]711;xft:Cousine:pixelsize=28\033\\ \033]712;xft:Cousine:pixelsize=28\033\\ \033]713;xft:Cousine:pixelsize=28\033\\" && clear
  nethack: ssh nethack@alt.org
  rc: bundle exec rails c
  res: echo $(tput cols)x$(tput lines)
  rs: bundle exec rails s
  s: tmux switch -t
  sign: git config commit.gpgsign true
  small: echo -e "\033]710;xft:Cousine:pixelsize=20\033\\ \033]711;xft:Cousine:pixelsize=20\033\\ \033]712;xft:Cousine:pixelsize=20\033\\ \033]713;xft:Cousine:pixelsize=20\033\\" && clear
  svndiff: 'svn diff --diff-cmd=colordiff --extensions=" -u --strip-trailing-cr --ignore-space-change " | less --quit-if-one-screen'
  t: tmux
  tiny: echo -e "\033]710;xft:Cousine:pixelsize=14\033\\ \033]711;xft:Cousine:pixelsize=14\033\\ \033]714;xft:Cousine:pixelsize=14\033\\ \033]713;xft:Cousine:pixelsize=14\033\\" && clear
  token: stoken | tail -n 1 | pbcopy
  ttf: ssh -tt kevingisi.com 'ssh -p 2210 localhost'
  v: vim
  vide: vim -c "NERDTreeToggle"
  vdot: (cd ~/.dotfiles && vim -c "NERDTreeToggle" vimrc) && up
  webs: python -m SimpleHTTPServer
  wifi: nmtui
  wiki: vim -c VimwikiIndex
  x: exit
  z: fg
symlinks:
  .Xdefaults: .dotfiles/Xdefaults
  .ackrc: .dotfiles/ackrc
  .gitconfig: .dotfiles/gitconfig
  .gitignore: .dotfiles/gitignore
  .gnupg/gpg.conf: .dotfiles/gpg.conf
  .ratpoisonrc: .dotfiles/ratpoisonrc
  .ssh/config: .dotfiles/ssh_config
  .tmux.conf: .dotfiles/tmux.conf
  .tmuxinator: .dotfiles/tmuxinator
  .vimrc: .dotfiles/vimrc
