aliases:
  vim: nvim
  z: fg
  ack: ag
  a: tmux attach
  t: todo.sh
symlinks:
  .config/nvim: .dotfiles/nvim
  .gitignore: .dotfiles/git/gitignore
  .gitconfig: .dotfiles/git/gitconfig
  .tmux.conf: .dotfiles/tmux/tmux.conf
