aliases:
  be: bundle exec
  webs: python -m SimpleHTTPServer
  dot: (cd ~/.dotfiles && vim bashrc && up)
  m: mux
  z: fg
symlinks:
  .vimrc: .dotfiles/vimrc
  .tmux.conf: .dotfiles/tmux.conf
  .gitconfig: .dotfiles/gitconfig
